### PR TITLE
Footer

### PR DESCRIPTION
**Pull request by nixpulvis**
After much thought and listening / watching users interact with the website, it's become clear to me that the form in the foot was confusing. This is a simple and clean footer.

### CODE REVIEW

**Comment by nixpulvis** [comment]
@ali Thoughts?

**Comment by ali** [comment]
> After much thought and listening / watching users interact with the website

Did you take any notes on this?

**Comment by nixpulvis** [comment]
Here's a few of my observed interactions. Josh also witnessed one.
1. A student pulled up the website on an iPad, he saw the join link (now a **much** more obvious button) and clicked it. This brought him to the signup page. On the signup page there was two forms for signing up, and he asked me which form to use.
2. I had 2 or 3 people ask me if they had to use the footer form, or if the footer form was different from the signup form. The website should not need explanation, and in general these questions were due to inconsistency.

I've put a link to signup in the footer, along with giving us space for things people would expect in a footer. Next because I do feel the signup link was not strong enough, I've made it a primary button. It's in the navbar still but it's **very** hard to miss.

**Comment by ali** [comment]
Can you post a before + after screenshot of the changes you're proposing?

**Comment by nixpulvis** [comment]
Before:
screen shot 2013-10-08 at 1 48 23 pm

After:
screen shot 2013-10-08 at 1 48 01 pm

**Comment by ali** [comment]
I don't think having two nav bars offers anyone anything. Can that footer be more useful? Can it make the site more engaging?

cc @aliceyoung9 @joshcaron

**Comment by nixpulvis** [comment]
This kind of secondary navigation for meta links is **very** common. So common in fact that most people generally expect it to be there.

That said I'm all for making it more engaging, the footer should be subtle though.

**Comment by nixpulvis** [comment]
Also it'd probably be a good idea to get rid of the duplicated links in the footer.

**Comment by ali** [comment]
I think footer-navs are the new sitemap, but I understand that's my opinion.

Just because it's common doesn't mean it's the way to go, especially if it's just echo-ing the nav at the top of the page.

**Comment by joshcaron** [comment]
Footer navs are good for SEO if we have a lot if pages and different areas to navigate to. But we don't have anything like a Privacy Policy or things like that, so I'm not sure how justified it is that we have one. If it was small enough I think it would be alright, especially once we have pages that get really long. 

I'm not opposed to the idea, but we should consider how it would affect the look and feel of the page and if it's really necessary. Also, what the level of effort it would be (probably not too much, but you never know). 

In regards to making the footer more engaging, I'm not too sure about that. Perhaps include a link to our latest/next event or something similar, but I'm not sure how effective it would be having a call to action in the footer.  

—

**Comment by nixpulvis** [comment]
I don't think dynamic content like links to events belongs in the footer. I was just thinking that if someone wanted to go crazy and have some fun. The footer could be a place to have random fun CSS/JS. Totally not required though.

**Comment by nixpulvis** [comment]
fixes #52

**Comment by ali** [comment]
@aliceyoung9 @joshcaron Thumbs up or down on this change?

**Comment by aceyoung9** [comment]
Can't see it...... Still trying to get this thing to build.....

Alice Young

**Comment by nixpulvis** [comment]
I'd love to help you if you're having problems. Also there are screenshots on this page if you want to base judgment on that.

**Comment by joshcaron** [comment]
Just saw the screenshots. I'd say merge this in for now, we can discuss the details of it when we go over a redesign for v2. But for now this will clear up confusion and make things look cleaner.

**Comment by nixpulvis** [comment]
Ok.

A point on versioning. This was version 2. Redesign will be version 2.1.

**Comment by joshcaron** [comment]
Also minor detail - copyright notice (though not even necessary) should be:

© {Year} {Organization}

**Comment by nixpulvis** [comment]
:up:

**Pull request merged**
