### PR TITLE
Admin controls

### PR DESCRIPTION
**Pull request by nixpulvis**
# Officer Promotion

Currently members are signing up without a password, so it's easy and fast. What this means however is that there is no frontend for the process to make a member with a password. We are going to expand this functionality to members later, but for now we **need** officers and they **need** passwords, so here we will build the officer promotion functionality.
### Promotion

When a member is promoted it will convert it's type to `Officer` and ensure that the officer is valid. This means there will be a password, and auth keys.
### Demotion

When an officer is demoted the class type will be changed to `SecureMember` and all position data will be removed. `Post` objects created by the officer will not be deleted however.
# Controls

This is the real start of the officer CMS for the site. Logging in as an officer will activate these additional view elements.
### Officer Nav

This will serve to visually show you that you are logged in on every page, and it holds links to logout and go to your member profile. More thing will be added here.
### Resource Views

In the views of every user facing resource (posts, events, etc) there will be appropriate actions (delete, edit, create, etc) and information (total count, next date, etc). These controls will be thematically dark, and distinguishable from other elements of the site.

To investigate this PR, please login as an officer and look at the index, show of members, events, and posts.

### CODE REVIEW

**Comment by nixpulvis** [comment]
@joshcaron @aliceyoung9 I want an icon to represent officership and fit in with glyphicons. Thoughts? Ideas?

**Comment by joshcaron** [comment]
image
image
image

**Comment by nixpulvis** [comment]
I kinda like the skull, even though the star maybe makes more sense.

**Comment by joshcaron** [comment]
The skull was my first choice, but I figured I should provide options.

**Comment by nixpulvis** [comment]
Those are not part of glyphicon halflings, so we don't have them right away.

**Comment by nixpulvis** [comment]
I think I'm going to roll Officer signup into this.

**Pull request merged**
