### PR TITLE
Error pages. Fixes #56

### LINKED ISSUE #56: Error Pages
This is the `public/404.html`, `public/422.html`, `public/500.html`. Currently they are the rails defaults, and this is bad.

### PR DESCRIPTION
**Pull request by aceyoung9**
Because sometimes :shit: happens, and when it does we send everyone to space.

:space_invader: :space_invader: :space_invader: :space_invader: :space_invader: :space_invader:

### CODE REVIEW

**Comment by nixpulvis** [comment]
I think the gray text is a bit unreadable, and the error code "Error XXX" should be large and more propionate. Other than that this is looking really cool.

Maybe just move the error description info into the smaller text.

**Comment by nixpulvis** [comment]
I'm starting to love this. Need to fix this though.

screen shot 2013-10-14 at 11 48 47 am

**Comment by aceyoung9** [comment]
OK my screen is tiny and I don't think I can work on this until I get back
in town. Should be a quick fix once I play with it.

**Comment by nixpulvis** [comment]
You should be able to fix this by just resizing your bowser all over the place, but if not we can wait a few days. It's a bad sign that we have a background color being set, and making the image positioned on the bottom.

**Comment by nixpulvis** [comment]
Ok I fixed it. We just need links now. I know that the logo is clickable, but there should be a more clear way to get home.

**Comment by nixpulvis** [comment]
I think this is good to go. Thoughts @ali @joshcaron @aliceyoung9 

screen shot 2013-10-16 at 1 49 13 am

**Comment by aceyoung9** [comment]
a:hover silliness and changed from that 0000ff blue.

Alice Young

**Comment by nixpulvis** [comment]
I'm not a huge fan of changing `font-style` on hover.

**Comment by nixpulvis** [comment]
:+1:

**Pull request merged**
